
# HTTP-specific options.
http:
  # Root Path http://{host}:{port}/xxx
  rootPath: /dropbox/*

    # Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'edu.sjsu.cmpe' to DEBUG.
    edu.sjsu.cmpe: DEBUG

  # Settings for logging to stdout.
  console:

    # If true, write log statements to stdout.
    enabled: true

    # Do not display log statements below this threshold to stdout.
    threshold: ALL

  # Settings for logging to a file.
  file:

    # If true, write log statements to a file.
    enabled: true

    # Do not write log statements below this threshold to the file.
    threshold: ALL
    
    # The file to which current statements will be logged.
    currentLogFilename: ./logs/dropbox.log
    
    # When the log file rotates, the archived log will be renamed to this and gzipped. The
    # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
    # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
    archivedLogFilenamePattern: ./logs/dropbox-%d.log.gz
    
    # The number of archived files to keep.
    archivedFileCount: 5

    # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
    timeZone: UTC

# HTTP-specific options.

#These are details of amazon
amazonTimeZone: "https://s3.us-west-1.amazonaws.com/"
amazonUsername: "AKIAJGHI3W5AFQQM2VJQ"
amazonPassword: "yQ2HoE7+gdwrQBaOylN0wiQaEV4q4AUmGxRYJAO4"
dbName: "dropbox"
dbCollection: "dropboxdetails"
databaseUsername: "cmpe273"
databasePassword: "123456"
databaseAddress: "ds053658.mongolab.com"
databasePort: 53658

# HTTP-specific options.
http:
  # Root Path http://{host}:{port}/xxx
  rootPath: /dropbox/*

# The port on which the HTTP server listens for service requests.
  port: 8050

  # The port on which the HTTP server listens for administrative requests.
  adminPort: 8082

